; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using the MEGA Prototyper.
[ MEGAinfo ]
ver                                = 7160126-x86_64 Linux              
[ DataSettings ]
datatype                           = snNucleotide                      
containsCodingNuc                  = False                             
MissingBaseSymbol                  = ?                                 
IdenticalBaseSymbol                = .                                 
GapSymbol                          = -                                 
[ ProcessTypes ]
ppInfer                            = true                              
ppNJ                               = true                              
[ AnalysisSettings ]
Analysis                           = Phylogeny Reconstruction          
Scope                              = All Selected Taxa                 
Statistical Method                 = Neighbor-joining                  
Phylogeny Test                     = Not Applicable                    
Test of Phylogeny                  = Bootstrap method                  
No. of Bootstrap Replications      = 1000                              
Substitution Model                 = ====================              
Substitutions Type                 = Nucleotide                        
Model/Method                       = No. of differences                
Substitutions to Include           = d: Transitions + Transversions    
Rates and Patterns                 = ====================              
Rates among Sites                  = Gamma Distributed With Invariant Sites (G+I)
Gamma Parameter                    = 4.00                              
Pattern among Lineages             = Same (Homogeneous)                
Data Subset to Use                 = ====================              
Gaps/Missing Data Treatment        = Complete deletion                 
Site Coverage Cutoff (%)           = Not Applicable                    
Has Time Limit                     = False                             
Maximum Execution Time             = -1                                
